handoff_hosts:
    financial_demo:
      title: "Financial Assistant"
      url: "http://52.188.160.175:5006"
    ## you can add more handoff hosts to this list e.g.
    # moodbot:
    #   title: "MoodBot"
    #   url: "http://localhost:5007"
